# Generated by Django 6.1 on 2026-08-15 20:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('school', models.CharField(max_length=70)),
                ('program', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coursework', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(unique=True)),
                ('category', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Regis Alain Udahemuka', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Rwanda 🇷🇼', max_length=50)),
                ('university', models.CharField(default='Ashesi Universiy', max_length=50)),
                ('program', models.CharField(default='BSc. Computer Science', max_length=50)),
                ('year', models.CharField(default='Sophomore', max_length=50)),
                ('focus', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('github', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('AI and data science', 'AI & Data Science'), ('web_development', 'Web Development'), ('tools', 'Tools & Platforms')], default='programming', max_length=50)),
                ('proficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currently_learning', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
