# Generated by Django 6.1 on 2026-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
